// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package composition

import (
	"fiber-service/api"
	"fiber-service/config"
	"fiber-service/domain/repository"
	"fiber-service/domain/service"
)

// Injectors from wire.go:

func Application() (api.Application, error) {
	databaseConfig := config.GetDatabaseConfig()
	dataSource, err := repository.NewDataSource(databaseConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(dataSource)
	userService := service.NewUserService(userRepository)
	orderRepository := repository.NewOrderRepository(dataSource)
	orderService := service.NewOrderService(orderRepository)
	serverConfig := config.GetServerConfig()
	application := api.NewApplication(userService, orderService, serverConfig)
	return application, nil
}
